'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto');const {JSDOM}=require('jsdom');const {HistoryDatabase,localDay}=require('../lib/history');const {Vault}=require('../lib/vault');const {validate}=require('../lib/validation');
const waitUntil=async predicate=>{const until=Date.now()+5000;while(!predicate()){if(Date.now()>until)throw new Error('DOM condition timed out');await new Promise(r=>setTimeout(r,10));}};
test('Panel DOM: 24 h, dostęp Brygadzisty, filtry, SVG, XSS, pełny XLSX i anulowanie eksportu',async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'andon-dom-'));const history=new HistoryDatabase(path.join(dir,'history.sqlite'),new Vault(crypto.randomBytes(32)));t.after(()=>history.close());const now=Date.now();const events=Array.from({length:237},(_,i)=>({id:crypto.randomUUID(),at:now-i*1000,type:'measurement',station:'y'+i%5,operator:i===0?'<img src=x onerror=alert(1)>':'Test',netSeconds:500+i,targetSeconds:600,cycleNumber:i+1,details:'=1+1'})).reverse();history.commit({},events);
 const html=fs.readFileSync(path.join(__dirname,'../public/control-panel.html'),'utf8');const dom=new JSDOM(html,{url:'http://127.0.0.1:3199/panelsterowania',runScripts:'outside-only',pretendToBeVisual:true});t.after(()=>dom.window.close());const w=dom.window,errors=[];w.addEventListener('error',e=>errors.push(e.message));w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.TextEncoder=TextEncoder;w.Blob=Blob;
 const listeners=new Map();let planned,blob,downloadName,downloadCount=0;w.URL.createObjectURL=b=>{blob=b;return 'blob:report';};w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=function(){downloadName=this.download;downloadCount++;};
 const socket={connected:false,on(event,fn){listeners.set(event,fn);},timeout(){return this;},disconnect(){this.connected=false;listeners.get('disconnect')?.('test');},emit(event,data,cb){let result;if(event==='historyQuery'||event==='historyExport')result=history.query(validate(event,data),event==='historyQuery');else if(event==='plannerAdd'){planned=validate(event,data);result={ok:true};}else throw new Error('Unexpected event: '+event);queueMicrotask(()=>cb(null,result));}};
 w.io=()=>socket;w.AndonAuth={async login(){return {employeeId:'test',userName:'Brygadzista testowy',roleName:'Brygadzista',role:'manager'};},async connect(){socket.connected=true;listeners.get('connect')?.();listeners.get('sync')?.({goal:15,netShiftMins:420,taktMins:28,shiftActive:false,shiftStart:null,shiftStopTime:now,serverTime:now,cycleTimes:[],planner:[],count:0});},async logout(){},requestId:()=>crypto.randomUUID()};
 for(const file of ['stations.js','support-sound.js','exporter.js','history-panel.js','control-panel.js'])new (require('node:vm').Script)(fs.readFileSync(path.join(__dirname,'../public',file),'utf8'),{filename:file}).runInContext(dom.getInternalVMContext());
 assert.deepEqual(errors,[]);assert.equal(w.document.querySelector('#plan-hour').options.length,25);assert.equal(w.document.querySelector('#plan-hour').options[24].value,'23');assert.equal(w.document.querySelector('#plan-minute').options.length,61);assert.equal(w.document.querySelector('#plan-time'),null);assert.equal(w.document.querySelector('#export'),null);
 const submit=id=>{const form=w.document.getElementById(id);form.dispatchEvent(new w.SubmitEvent('submit',{bubbles:true,cancelable:true,submitter:form.querySelector('button[type=submit]')}));};
 w.document.getElementById('access-code').value='12345678';submit('login-form');await waitUntil(()=>socket.connected);
 w.document.getElementById('plan-date').value='2027-01-10';w.document.getElementById('plan-hour').value='23';w.document.getElementById('plan-minute').value='05';submit('planner-form');await waitUntil(()=>Boolean(planned));assert.equal(planned.time,'23:05');
 w.document.getElementById('reports-tab').click();await waitUntil(()=>w.document.getElementById('history-rows').children.length===50);assert.equal(w.document.getElementById('reports').hidden,false);assert.equal(w.document.getElementById('people-tab').hidden,true);assert.equal(w.document.getElementById('history-measurements').textContent,'237');assert(w.document.querySelector('#history-stations-chart svg'));assert.equal(w.document.querySelector('#history-rows img'),null);assert(w.document.getElementById('history-rows').textContent.includes('<img src=x onerror=alert(1)>'));
 w.document.getElementById('history-period').value='month';submit('history-form');await waitUntil(()=>w.document.getElementById('history-range').textContent.includes(' — '));assert(w.document.getElementById('history-range').textContent.includes(localDay(now).slice(0,7)+'-01'));
 w.document.getElementById('history-export').click();await waitUntil(()=>downloadCount===1);assert(downloadName.endsWith('.xlsx'));const bytes=Buffer.from(await blob.arrayBuffer());let offset=0,sheet;while(bytes.readUInt32LE(offset)===0x04034b50){const size=bytes.readUInt32LE(offset+18),nameSize=bytes.readUInt16LE(offset+26),extra=bytes.readUInt16LE(offset+28),name=bytes.toString('utf8',offset+30,offset+30+nameSize),start=offset+30+nameSize+extra;if(name==='xl/worksheets/sheet1.xml')sheet=bytes.toString('utf8',start,start+size);offset=start+size;}assert(sheet);assert.equal((sheet.match(/<row /g)||[]).length,238);assert(sheet.includes('&lt;img'));assert(!sheet.includes('<f>'));assert(sheet.includes('=1+1'));
 w.document.getElementById('history-export').click();await new Promise(r=>setTimeout(r,20));w.document.getElementById('logout').click();await waitUntil(()=>w.document.getElementById('workspace').hidden);await new Promise(r=>setTimeout(r,250));assert.equal(downloadCount,1);assert.equal(w.document.getElementById('history-rows').children.length,0);assert.deepEqual(errors,[]);
});
