'use strict';
process.env.TZ='Europe/Warsaw';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {HistoryDatabase,rangeFor,periodKeys}=require('../lib/history');const {Vault}=require('../lib/vault');const {Line}=require('../lib/line');const {validate}=require('../lib/validation');const {createApplication}=require('../lib/server-app');const {configFrom}=require('../lib/config');const {io}=require('socket.io-client');
const dir=()=>fs.mkdtempSync(path.join(os.tmpdir(),'andon-history-'));const key=()=>new Vault(crypto.randomBytes(32));const request=()=>({requestId:crypto.randomUUID()});const query=(extra={})=>validate('historyQuery',{period:'day',date:'2026-09-13',...extra});
const row=(at,type='measurement',extra={})=>({id:crypto.randomUUID(),at:new Date(at).getTime(),type,station:'y0',operator:'Osoba testowa',netSeconds:70,targetSeconds:100,...extra});
function setup(t){const root=dir(),vault=key(),history=new HistoryDatabase(path.join(root,'history.sqlite'),vault);t.after(()=>history.close());return {root,vault,history};}
test('Historia: zapis SQL jest trwały, zaszyfrowany i używa indeksów bez jawnych dat',t=>{const {root,vault,history}=setup(t);history.commit({schema:2},[row('2026-09-13T10:00:00+02:00')]);history.checkpoint();const bytes=fs.readFileSync(path.join(root,'history.sqlite'));assert(!bytes.includes(Buffer.from('Osoba testowa')));assert(!bytes.includes(Buffer.from('2026-09-13')));assert.equal(history.query(query()).total,1);assert.equal(history.query(query()).rows[0].operator,'Osoba testowa');assert.throws(()=>new HistoryDatabase(path.join(root,'history.sqlite'),key()));const reopened=new HistoryDatabase(path.join(root,'history.sqlite'),vault);assert.equal(reopened.query(query()).total,1);reopened.close();});
test('Historia: tydzień poniedziałek–niedziela, granice roku i miesiąca',()=>{assert.equal(periodKeys('2026-01-01').week,'2025-12-29');assert.deepEqual(rangeFor(query({period:'week',date:'2026-01-01'})),{start:'2025-12-29',end:'2026-01-04',key:'2025-12-29',label:'2025-12-29 — 2026-01-04'});assert.equal(rangeFor(query({period:'month',date:'2028-02-19'})).end,'2028-02-29');assert.throws(()=>query({date:'2026-02-30'}));assert.throws(()=>query({station:"y0' OR 1=1 --"}));assert.throws(()=>query({period:'year'}));});
test('Historia: filtry okresu i stanowiska, metryki oraz polska strefa czasowa',t=>{const {history}=setup(t);history.commit({},[row('2026-09-12T22:30:00Z'),row('2026-09-13T12:00:00+02:00','measurement',{station:'y1',netSeconds:150}),row('2026-09-13T12:00:00+02:00','cycle',{station:null,downSeconds:50}),row('2026-09-13T13:00:00+02:00','callSupport',{details:'Brak Materiału · brak opakowań'}),row('2026-09-14T10:00:00+02:00')]);const day=history.query(query());assert.equal(day.total,4);assert.equal(day.summary.measurements,2);assert.equal(day.summary.averageSeconds,110);assert.equal(day.summary.onTimePercent,50);assert.equal(day.summary.cycles,1);assert.equal(day.summary.downSeconds,50);assert.equal(day.summary.buckets[0].label,'00:00');assert.equal(history.query(query({station:'y0'})).total,2);assert.equal(history.query(query({period:'week'})).total,4);assert.equal(history.query(query({period:'month'})).total,5);});
test('Historia: stabilna paginacja i eksport mimo napływu nowych zapisów',t=>{const {history}=setup(t);history.commit({},Array.from({length:7},(_,i)=>row('2026-09-13T10:00:00+02:00','measurement',{cycleNumber:i+1})));const first=history.query(query({limit:3}));history.commit({},[row('2026-09-13T10:00:01+02:00')]);const second=history.query(query({limit:3,page:2,watermark:first.watermark}));assert.equal(first.total,7);assert.equal(second.total,7);assert.equal(history.query(query()).total,8);assert.equal(new Set([...first.rows,...second.rows].map(r=>r.id)).size,6);const exported=history.query(query({limit:200,order:'asc',watermark:first.watermark}),false);assert.equal(exported.rows.length,7);assert.equal(exported.rows[0].cycleNumber,1);assert(!Object.hasOwn(exported,'summary'));});
test('Historia i stan linii zatwierdzają się w jednej transakcji',t=>{const {history,vault,root}=setup(t);let now=new Date('2026-09-13T07:00:00+02:00').getTime();const file=path.join(root,'line.json'),line=new Line(file,vault,()=>Date.now(),history);line.clock=()=>now;const owner={id:crypto.randomUUID(),name:'Test',role:'owner'};line.change('shiftStart',request(),owner,'panel');const old=structuredClone(line.state),max=history.maxSeq();const write=history.writeEvent;history.writeEvent=()=>{throw new Error('failure');};assert.throws(()=>line.change('actionOK',{cycleId:line.state.cycleId,...request()},owner,'y0'));assert.deepEqual(line.state,old);assert.deepEqual(history.readState(),old);assert.equal(history.maxSeq(),max);history.writeEvent=write;const data={cycleId:line.state.cycleId,...request()};line.change('actionOK',data,owner,'y0');line.change('actionOK',data,owner,'y0');assert.equal(history.query(query({category:'measurement'})).total,1);line.change('shiftStop',request(),owner,'panel');line.change('shiftStart',request(),owner,'panel');assert.equal(line.state.cycleTimes.length,0);assert.equal(history.query(query({category:'measurement'})).total,1);const second=new Line(file,vault,()=>Date.now(),history);assert.equal(second.state.shiftId,line.state.shiftId);});
test('Starsze pomiary bez daty są importowane jeden raz do osobnego widoku',t=>{const {history}=setup(t);const state={cycleTimes:[{s:'Y2',t:1,m:'2m 3s',ts:'23:50:00'}],logs:[]};history.bootstrap(state);history.bootstrap(state);const result=history.query(query({period:'undated'}));assert.equal(result.total,1);assert.equal(result.rows[0].at,null);assert.equal(result.rows[0].netSeconds,123);assert.equal(result.rows[0].targetSeconds,null);assert.equal(history.query(query()).total,0);});
test('Usunięta baza nie jest odtwarzana jako puste archiwum',t=>{const {history,vault,root}=setup(t);const file=path.join(root,'line.json');vault.write(file,{schema:3,historyDatabase:true},'line');assert.throws(()=>new Line(file,vault,Date.now,history),/Brak bazy historii/);});
test('API historii: wyłącznie panel z rolą Właściciela lub Brygadzisty',async t=>{const root=dir(),config=configFrom({PORT:'0',ANDON_DATA_DIR:path.join(root,'data'),ANDON_STATE_FILE:path.join(root,'line'),ANDON_MASTER_KEY:crypto.randomBytes(32).toString('base64')},path.resolve(__dirname,'..'));const app=await createApplication(config);t.after(()=>app.close());const address=await app.listen(),url='http://127.0.0.1:'+address.port;config.origins=[url];
 async function connect(code,view){const anon=await fetch(url+'/api/session',{headers:{Origin:url}}),cookie=anon.headers.get('set-cookie').split(';')[0],csrf=(await anon.json()).csrfToken;const logged=await fetch(url+'/api/login',{method:'POST',headers:{Origin:url,Cookie:cookie,'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({code})});const auth=await logged.json();const socket=io(url,{autoConnect:false,reconnection:false,transports:['websocket'],extraHeaders:{Origin:url,Cookie:logged.headers.get('set-cookie').split(';')[0]},auth:{view,csrfToken:auth.csrfToken}});t.after(()=>socket.disconnect());await new Promise((resolve,reject)=>{socket.once('sync',resolve);socket.once('connect_error',reject);socket.connect();});return socket;}
 const emit=(s,event,data)=>new Promise((resolve,reject)=>s.timeout(3000).emit(event,data,(e,r)=>e?reject(e):resolve(r)));
 const employee=await connect('10399071','y0');assert.equal((await emit(employee,'historyQuery',query())).ok,false);assert.equal((await emit(employee,'historyExport',query())).ok,false);const owner=await connect('10182672','panel');assert.equal((await emit(owner,'historyQuery',query())).ok,true);assert.equal((await emit(owner,'historyQuery',{...query(),role:'owner'})).code,'INVALID_INPUT');assert.equal((await emit(owner,'historyQuery',{...query(),limit:201})).code,'INVALID_INPUT');const ownerId=app.accounts.state.users.find(u=>u.role==='owner').id;await app.accounts.mutate(ownerId,'create',{number:'12345678',name:'Brygadzista test',role:'manager',active:true,allowedStations:['y0'],version:app.accounts.state.version});const manager=await connect('12345678','panel');assert.equal((await emit(manager,'historyQuery',query())).ok,true);
});
