'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto');
const {summarize}=require('../lib/report-summary');const {HistoryDatabase,rangeFor,localDay}=require('../lib/history');const {Vault}=require('../lib/vault');const {validate}=require('../lib/validation');
const q=(overrides={})=>validate('historyQuery',{period:'day',date:'2026-09-13',...overrides});
const e=(type,extra={})=>({id:crypto.randomUUID(),at:new Date('2026-09-13T10:00:00+02:00').getTime(),type,station:'y0',details:'',...extra});
const analyse=events=>summarize(events,q(),rangeFor(q()));
test('Analiza: mediana, P90 i ocena każdego pomiaru względem jego własnego taktu',()=>{const s=analyse([e('measurement',{netSeconds:50,targetSeconds:100}),e('measurement',{netSeconds:200,targetSeconds:100}),e('measurement',{netSeconds:30,targetSeconds:1000}),e('measurement',{netSeconds:100,targetSeconds:null})]);const st=s.stations[0];assert.equal(st.medianSeconds,75);assert.equal(st.p90Seconds,200);assert.equal(st.medianTaktPercent,50);assert.equal(st.p90TaktPercent,200);assert.equal(st.timed,3);assert.equal(st.unknown,1);assert.equal(st.late,1);assert.equal(s.onTimePercent,200/3);assert.equal(s.attentionStation,'y0');});
test('Analiza: brak i błędny takt nie oznacza terminowości ani zerowego czasu',()=>{const s=analyse([e('measurement',{netSeconds:0,targetSeconds:100}),e('measurement',{netSeconds:100,targetSeconds:100}),e('measurement',{netSeconds:100,targetSeconds:0}),e('measurement',{netSeconds:-1,targetSeconds:100}),e('measurement',{netSeconds:null,targetSeconds:100})]);assert.equal(s.timedMeasurements,2);assert.equal(s.onTimePercent,100);assert.equal(s.unknownMeasurements,3);assert.equal(s.invalidMeasurements,2);assert.equal(s.stations[0].medianSeconds,100);assert.equal(s.stations[1].medianSeconds,null);assert.equal(s.stations[1].latePercent,null);assert.equal(s.attentionStation,null);});
test('Analiza: opóźnienia linii nie sumują opóźnień jej stanowisk',()=>{const s=analyse([e('cycle',{netSeconds:200,targetSeconds:100,downSeconds:100}),e('cycle',{netSeconds:100,targetSeconds:100,downSeconds:0}),e('cycle',{netSeconds:104,targetSeconds:null,downSeconds:4}),e('shiftStop',{downSeconds:5}),e('measurement',{netSeconds:500,targetSeconds:100,downSeconds:400}),e('downStart',{downSeconds:700})]);assert.equal(s.cycles,3);assert.equal(s.cycleOnTime,1);assert.equal(s.cycleLate,1);assert.equal(s.unknownCycleTarget,1);assert.equal(s.cycleOnTimePercent,50);assert.equal(s.downSeconds,109);assert.equal(s.buckets[10].downSeconds,109);assert.equal(s.buckets[10].cycleUnknown,1);});
test('Analiza: Pareto przyczyn liczy wezwania, pomija anulowania i ponowienia',()=>{const events=[];for(const [reason,count] of [['Brak Materiału',11],['Awaria Maszyny',6],['Wada materiału',3]])for(let i=0;i<count;i++)events.push(e('callSupport',{details:reason+' · komentarz'}));for(let i=0;i<10;i++)events.push(e('notificationRetry'),e('cancelSupport'));const s=analyse(events);assert.equal(s.support,20);assert.deepEqual(s.reasons.map(r=>r.sharePercent),[55,30,15]);assert.deepEqual(s.reasons.map(r=>r.cumulativePercent),[55,85,100]);assert.deepEqual(s.reasons.map(r=>r.priority),[true,true,false]);});
test('Analiza: filtry rejestru nie zmieniają wykresów ani ich próbki',t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'andon-chart-')),h=new HistoryDatabase(path.join(dir,'history.sqlite'),new Vault(crypto.randomBytes(32)));t.after(()=>h.close());h.commit({},[e('measurement',{netSeconds:50,targetSeconds:100}),e('measurement',{station:'y1',netSeconds:150,targetSeconds:100}),e('cycle',{station:null,netSeconds:150,targetSeconds:100,downSeconds:50}),e('callSupport',{details:'Awaria Maszyny'})]);const all=h.query(q()),filtered=h.query(q({station:'y0',category:'measurement'})),none=h.query(q({station:'y4',category:'support'}));assert.equal(filtered.total,1);assert.equal(none.total,0);assert.deepEqual(filtered.summary,all.summary);assert.deepEqual(none.summary,all.summary);assert.equal(all.summary.scope,'period-all-stations');});
test('Analiza: puste dane i import bez daty nie tworzą fałszywej osi czasu',()=>{const empty=analyse([]);assert.equal(empty.onTimePercent,null);assert.equal(empty.cycleOnTimePercent,null);assert(empty.stations.every(s=>s.p90Seconds===null));const query=q({period:'undated'}),s=summarize([e('measurement',{at:null,netSeconds:50,targetSeconds:null})],query,rangeFor(query));assert.equal(s.buckets.length,0);assert.equal(s.stations[0].medianSeconds,50);assert.equal(s.timedMeasurements,0);});
test('Wykresy DOM: próbki, etykiety, szczegóły klawiaturą, ranking i brak danych',async t=>{
 const {JSDOM}=require('jsdom'),vm=require('node:vm');const root=path.resolve(__dirname,'..'),dom=new JSDOM(fs.readFileSync(path.join(root,'public/control-panel.html'),'utf8'),{runScripts:'outside-only',url:'http://localhost/panelsterowania'}),w=dom.window;t.after(()=>w.close());const errors=[];w.addEventListener('error',e=>errors.push(e.message));const sample=[];
 for(let h=6;h<18;h++){for(let n=0;n<(h%5)+1;n++)sample.push(e('cycle',{at:new Date('2026-09-13T'+String(h).padStart(2,'0')+':20:00+02:00').getTime(),netSeconds:n%2?700:550,targetSeconds:n%3===2?null:600,downSeconds:n%2?100:0}));}
 for(let station=0;station<4;station++)for(let i=0;i<20;i++)sample.push(e('measurement',{station:'y'+station,netSeconds:station===2?450+i*20:300+i*12,targetSeconds:i%8===0?null:600}));for(let i=0;i<20;i++)sample.push(e('callSupport',{details:i<11?'Brak Materiału':i<17?'Awaria Maszyny':'Wada materiału'}));
 const summary=analyse(sample);let empty=false;w.__request=async()=>({ok:true,summary:empty?analyse([]):summary,rows:[],total:0,page:1,limit:50,range:{label:'13.09.2026'},undated:0,watermark:100});w.__identity=()=>({role:'owner'});
 new vm.Script(fs.readFileSync(path.join(root,'public/stations.js'),'utf8')).runInContext(dom.getInternalVMContext());
 new vm.Script(fs.readFileSync(path.join(root,'public/history-panel.js'),'utf8')).runInContext(dom.getInternalVMContext());new vm.Script('HistoryPanel.init(window.__request,window.__identity);HistoryPanel.open();').runInContext(dom.getInternalVMContext());await new Promise(r=>setImmediate(r));
 assert.equal(w.document.querySelector('label[for=plan-hour]').textContent,'Godzina');assert(!w.document.querySelector('.history-hint'));assert.equal(w.document.querySelector('#history-form #history-station'),null);assert(w.document.querySelector('.registry-filters #history-station'));
 for(const id of ['history-production-chart','history-stations-chart','history-downtime-chart'])assert(w.document.querySelector('#'+id+' svg'));
 assert(w.document.getElementById('stations-insight').textContent.includes('X2'));assert(w.document.getElementById('history-station-metrics').textContent.includes('X4'));assert.equal(w.document.querySelectorAll('.pareto-priority').length,2);assert(w.document.getElementById('history-support-chart').textContent.includes('85%'));
 const focus=w.document.querySelector('#history-production-chart [tabindex]');focus.dispatchEvent(new w.Event('focus'));assert(w.document.getElementById('production-detail').textContent.includes('cykli:'));
 const station=w.document.querySelector('#history-stations-chart [tabindex]');station.dispatchEvent(new w.Event('focus'));assert(w.document.getElementById('stations-detail').textContent.includes('ocenionych pomiarów'));assert(w.document.getElementById('history-on-time-note').textContent.includes('bez oceny: 12'));
 if(process.env.ANDON_CHART_QA_DIR){fs.mkdirSync(process.env.ANDON_CHART_QA_DIR,{recursive:true});for(const id of ['history-production-chart','history-stations-chart','history-downtime-chart']){const svg=w.document.querySelector('#'+id+' svg').outerHTML;fs.writeFileSync(path.join(process.env.ANDON_CHART_QA_DIR,id+'.svg'),svg);}fs.writeFileSync(path.join(process.env.ANDON_CHART_QA_DIR,'rendered-dom.html'),dom.serialize());}
 empty=true;new vm.Script('HistoryPanel.open();').runInContext(dom.getInternalVMContext());await new Promise(r=>setImmediate(r));assert.equal(w.document.getElementById('history-on-time').textContent,'—');assert.equal(w.document.querySelectorAll('.refined-charts svg').length,0);assert(w.document.getElementById('history-stations-chart').textContent.includes('Brak pomiarów'));assert.deepEqual(errors,[]);
});
